<!-- 
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Softprodigy
 * @package    Softprodigy_Socialshare
 * @copyright  Copyright (c) 2014 SoftProdigy <magento@softprodigy.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 -->
<?php $position = Mage::getStoreConfig('socialshare/general/social_position'); ?>
<div class="social-share-<?php if($position == 1){ ?>left<?php } else if($position == 2){ ?>right <?php } ?>">
		<?php $links = Mage::getModel('socialshare/socialshare_product')->getCollection()->addAttributeToSort('socialshare_position', 'asc');
			foreach($links as $index)
			{
				$link = Mage::getModel('socialshare/socialshare_product')->load($index->getId());
				if($link->getSocialshareStatus() == 1)
				{
					$params = array();
					$url = $link->getSocialshareLink();
					$current_url = Mage::helper('core/url')->getCurrentUrl();
					if(strpos($url, "URI"))
					{
						
						$f_url = str_replace('URI',$current_url,$url);
					}
					else
					{
						$f_url = $url;
					}	
		?>
					<div class="social-popout">
						<a href="<?php echo $f_url;?>" target="_blank"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$link->getSocialshareImage();?>" alt="<?php echo $link->getSocialshareName();?>" title="<?php echo $link->getSocialshareTitle();?>" /></a>
					</div>
		<?php	} 
			} //---End of foreach
		?>
</div>
